"""
定义各种提示词，便于系统调用
"""

# 导入新的功能模块提示词
from app.prompts.parsing import (
    PARSING_SYSTEM_PROMPT, PARSING_USER_PROMPT,
    TEXT_PARSING_SYSTEM_PROMPT, TEXT_PARSING_USER_PROMPT,
    EXCEL_PARSING_SYSTEM_PROMPT, EXCEL_PARSING_USER_PROMPT,
    KB_PARSING_SYSTEM_PROMPT, KB_PARSING_USER_PROMPT,
    FILE_PARSING_SYSTEM_PROMPT, FILE_PARSING_USER_PROMPT,
    DB_PARSING_SYSTEM_PROMPT, DB_PARSING_USER_PROMPT
)

from app.prompts.querying import (
    QUERY_SYSTEM_PROMPT, QUERY_USER_PROMPT,
    SQL_QUERY_SYSTEM_PROMPT, SQL_QUERY_USER_PROMPT,
    KB_QUERY_SYSTEM_PROMPT, KB_QUERY_USER_PROMPT,
    TEXT_QUERY_SYSTEM_PROMPT, TEXT_QUERY_USER_PROMPT,
    DATABASE_SCHEMA_PROMPT
)

from app.prompts.analyzing import (
    ANALYSIS_SYSTEM_PROMPT, ANALYSIS_USER_PROMPT,
    DATA_ANALYSIS_SYSTEM_PROMPT, DATA_ANALYSIS_USER_PROMPT,
    TEXT_ANALYSIS_SYSTEM_PROMPT, TEXT_ANALYSIS_USER_PROMPT,
    EXCEL_ANALYSIS_SYSTEM_PROMPT, EXCEL_ANALYSIS_USER_PROMPT,
    FILE_ANALYSIS_SYSTEM_PROMPT, FILE_ANALYSIS_USER_PROMPT,
    KB_ANALYSIS_SYSTEM_PROMPT, KB_ANALYSIS_USER_PROMPT
)

from app.prompts.responding import (
    RESPONSE_SYSTEM_PROMPT, RESPONSE_USER_PROMPT,
    DATA_RESPONSE_SYSTEM_PROMPT, DATA_RESPONSE_USER_PROMPT,
    TEXT_RESPONSE_SYSTEM_PROMPT, TEXT_RESPONSE_USER_PROMPT,
    KB_RESPONSE_SYSTEM_PROMPT, KB_RESPONSE_USER_PROMPT,
    COMPREHENSIVE_RESPONSE_SYSTEM_PROMPT, COMPREHENSIVE_RESPONSE_USER_PROMPT
)

# 定义向后兼容的别名
TEXT_SYSTEM_PROMPT = TEXT_ANALYSIS_SYSTEM_PROMPT
TEXT_USER_PROMPT = TEXT_ANALYSIS_USER_PROMPT
EXCEL_SYSTEM_PROMPT = EXCEL_ANALYSIS_SYSTEM_PROMPT
EXCEL_USER_PROMPT = EXCEL_ANALYSIS_USER_PROMPT
DATABASE_SYSTEM_PROMPT = DATABASE_SCHEMA_PROMPT
DATABASE_USER_PROMPT = SQL_QUERY_USER_PROMPT
KNOWLEDGE_BASE_SYSTEM_PROMPT = KB_ANALYSIS_SYSTEM_PROMPT
KNOWLEDGE_BASE_USER_PROMPT = KB_ANALYSIS_USER_PROMPT
OLD_RESPONSE_SYSTEM_PROMPT = RESPONSE_SYSTEM_PROMPT
OLD_RESPONSE_USER_PROMPT = RESPONSE_USER_PROMPT
OLD_DATA_ANALYSIS_SYSTEM_PROMPT = DATA_ANALYSIS_SYSTEM_PROMPT
OLD_DATA_ANALYSIS_USER_PROMPT = DATA_ANALYSIS_USER_PROMPT
OLD_TEXT_ANALYSIS_SYSTEM_PROMPT = TEXT_ANALYSIS_SYSTEM_PROMPT
OLD_TEXT_ANALYSIS_USER_PROMPT = TEXT_ANALYSIS_USER_PROMPT
OLD_EXCEL_ANALYSIS_SYSTEM_PROMPT = EXCEL_ANALYSIS_SYSTEM_PROMPT
OLD_EXCEL_ANALYSIS_USER_PROMPT = EXCEL_ANALYSIS_USER_PROMPT
OLD_FILE_ANALYSIS_SYSTEM_PROMPT = FILE_ANALYSIS_SYSTEM_PROMPT
OLD_FILE_ANALYSIS_USER_PROMPT = FILE_ANALYSIS_USER_PROMPT
OLD_KNOWLEDGE_BASE_SYSTEM_PROMPT = KB_ANALYSIS_SYSTEM_PROMPT
OLD_KNOWLEDGE_BASE_USER_PROMPT = KB_ANALYSIS_USER_PROMPT
OLD_DATABASE_SCHEMA_PROMPT = DATABASE_SCHEMA_PROMPT
OLD_DATABASE_SCHEMA_USER_PROMPT = SQL_QUERY_USER_PROMPT

# 导出所有提示词
__all__ = [
    # 解析模块提示词
    'PARSING_SYSTEM_PROMPT', 'PARSING_USER_PROMPT',
    'TEXT_PARSING_SYSTEM_PROMPT', 'TEXT_PARSING_USER_PROMPT',
    'EXCEL_PARSING_SYSTEM_PROMPT', 'EXCEL_PARSING_USER_PROMPT',
    'KB_PARSING_SYSTEM_PROMPT', 'KB_PARSING_USER_PROMPT',
    'FILE_PARSING_SYSTEM_PROMPT', 'FILE_PARSING_USER_PROMPT',
    'DB_PARSING_SYSTEM_PROMPT', 'DB_PARSING_USER_PROMPT',
    
    # 查询模块提示词
    'QUERY_SYSTEM_PROMPT', 'QUERY_USER_PROMPT',
    'SQL_QUERY_SYSTEM_PROMPT', 'SQL_QUERY_USER_PROMPT',
    'KB_QUERY_SYSTEM_PROMPT', 'KB_QUERY_USER_PROMPT', 
    'TEXT_QUERY_SYSTEM_PROMPT', 'TEXT_QUERY_USER_PROMPT',
    'DATABASE_SCHEMA_PROMPT',
    
    # 分析模块提示词
    'ANALYSIS_SYSTEM_PROMPT', 'ANALYSIS_USER_PROMPT',
    'DATA_ANALYSIS_SYSTEM_PROMPT', 'DATA_ANALYSIS_USER_PROMPT',
    'TEXT_ANALYSIS_SYSTEM_PROMPT', 'TEXT_ANALYSIS_USER_PROMPT',
    'EXCEL_ANALYSIS_SYSTEM_PROMPT', 'EXCEL_ANALYSIS_USER_PROMPT',
    'FILE_ANALYSIS_SYSTEM_PROMPT', 'FILE_ANALYSIS_USER_PROMPT',
    'KB_ANALYSIS_SYSTEM_PROMPT', 'KB_ANALYSIS_USER_PROMPT',
    
    # 回复模块提示词
    'RESPONSE_SYSTEM_PROMPT', 'RESPONSE_USER_PROMPT',
    'DATA_RESPONSE_SYSTEM_PROMPT', 'DATA_RESPONSE_USER_PROMPT',
    'TEXT_RESPONSE_SYSTEM_PROMPT', 'TEXT_RESPONSE_USER_PROMPT',
    'KB_RESPONSE_SYSTEM_PROMPT', 'KB_RESPONSE_USER_PROMPT',
    'COMPREHENSIVE_RESPONSE_SYSTEM_PROMPT', 'COMPREHENSIVE_RESPONSE_USER_PROMPT',
    
    # 向后兼容的提示词别名
    'TEXT_SYSTEM_PROMPT', 'TEXT_USER_PROMPT',
    'EXCEL_SYSTEM_PROMPT', 'EXCEL_USER_PROMPT',
    'DATABASE_SYSTEM_PROMPT', 'DATABASE_USER_PROMPT',
    'KNOWLEDGE_BASE_SYSTEM_PROMPT', 'KNOWLEDGE_BASE_USER_PROMPT',
    'OLD_RESPONSE_SYSTEM_PROMPT', 'OLD_RESPONSE_USER_PROMPT',
    'OLD_DATA_ANALYSIS_SYSTEM_PROMPT', 'OLD_DATA_ANALYSIS_USER_PROMPT',
    'OLD_TEXT_ANALYSIS_SYSTEM_PROMPT', 'OLD_TEXT_ANALYSIS_USER_PROMPT',
    'OLD_EXCEL_ANALYSIS_SYSTEM_PROMPT', 'OLD_EXCEL_ANALYSIS_USER_PROMPT',
    'OLD_FILE_ANALYSIS_SYSTEM_PROMPT', 'OLD_FILE_ANALYSIS_USER_PROMPT',
    'OLD_KNOWLEDGE_BASE_SYSTEM_PROMPT', 'OLD_KNOWLEDGE_BASE_USER_PROMPT',
    'OLD_DATABASE_SCHEMA_PROMPT', 'OLD_DATABASE_SCHEMA_USER_PROMPT'
] 