"""
提示词模板模块
"""
from app.prompts.database import DATABASE_SYSTEM_PROMPT, DATABASE_USER_PROMPT
from app.prompts.response import RESPONSE_SYSTEM_PROMPT, RESPONSE_USER_PROMPT
from app.prompts.excel import EXCEL_SYSTEM_PROMPT, EXCEL_USER_PROMPT
from app.prompts.text import TEXT_SYSTEM_PROMPT, TEXT_USER_PROMPT
from app.prompts.file_analysis import FILE_ANALYSIS_SYSTEM_PROMPT, FILE_ANALYSIS_USER_PROMPT
from app.prompts.knowledge_base import KNOWLEDGE_BASE_SYSTEM_PROMPT, KNOWLEDGE_BASE_USER_PROMPT

__all__ = [
    'DATABASE_SYSTEM_PROMPT',
    'DATABASE_USER_PROMPT',
    'RESPONSE_SYSTEM_PROMPT',
    'RESPONSE_USER_PROMPT',
    'EXCEL_SYSTEM_PROMPT',
    'EXCEL_USER_PROMPT',
    'TEXT_SYSTEM_PROMPT',
    'TEXT_USER_PROMPT',
    'FILE_ANALYSIS_SYSTEM_PROMPT',
    'FILE_ANALYSIS_USER_PROMPT',
    'KNOWLEDGE_BASE_SYSTEM_PROMPT',
    'KNOWLEDGE_BASE_USER_PROMPT'
] 